# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: SpayUp
description: "Apps for Corrective and Preventive Action"
keywords: "spayup, corrective, preventive, action, cpa, free, app, download"

# Site settings
url: http://arinsuga.com
baseurl: "/spayup"

# Download settings
download:
  source  : https://github.com/sugadotnet/spayup/archive/master.zip
  release : https://github.com/sugadotnet/spayup

# Author settings
author:
  name      : Arin Suga
  job       : Professional Application Development Consultant
  bio       : "Enthusiast and friendly, your friend to build a good application."
  thumb     : /images/author.jpg
  email     : arinsuga@gmail.com
  url       : http://arinsuga.com
  github    : https://github.com/sugaprivate
  linkedin  : https://www.linkedin.com/in/arin-suga-941076a5/

# google_analytics: UA-52446115-1
repo: https://github.com/sugadotnet/spayup

# comments
disqus_shortname: "arinsuga"
